# Generated by Django 4.1.2 on 2022-11-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProBlog", "0002_post_post_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="General", max_length=255),
        ),
    ]
