# Generated by Django 4.1.2 on 2022-12-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProBlog", "0005_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.CharField(default="Click Above to View", max_length=255),
        ),
    ]
