# Generated by Django 4.1.2 on 2022-12-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProBlog", "0009_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile/"),
        ),
    ]
